/* Generated By:JavaCC: Do not edit this line. analisa_LPDConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface analisa_LPDConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ATRIBUICAO = 1;
  /** RegularExpression Id. */
  int MAIS = 2;
  /** RegularExpression Id. */
  int MENOS = 3;
  /** RegularExpression Id. */
  int MULT = 4;
  /** RegularExpression Id. */
  int DIV = 5;
  /** RegularExpression Id. */
  int PROGRAMA = 6;
  /** RegularExpression Id. */
  int INICIO = 7;
  /** RegularExpression Id. */
  int FIM = 8;
  /** RegularExpression Id. */
  int ESCREVA = 9;
  /** RegularExpression Id. */
  int VAR = 10;
  /** RegularExpression Id. */
  int FECHAPARENTESES = 11;
  /** RegularExpression Id. */
  int ABREPARENTESES = 12;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 13;
  /** RegularExpression Id. */
  int VIRGULA = 14;
  /** RegularExpression Id. */
  int PONTO = 15;
  /** RegularExpression Id. */
  int INTEIRO = 16;
  /** RegularExpression Id. */
  int BOOLEANO = 17;
  /** RegularExpression Id. */
  int NUMERO = 18;
  /** RegularExpression Id. */
  int VERDADEIRO = 19;
  /** RegularExpression Id. */
  int FALSO = 20;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 21;
  /** RegularExpression Id. */
  int DOIS_PONTOS = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"programa\"",
    "\"inicio\"",
    "\"fim\"",
    "\"escreva\"",
    "\"var\"",
    "\")\"",
    "\"(\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"inteiro\"",
    "\"booleano\"",
    "<NUMERO>",
    "\"verdadeiro\"",
    "\"falso\"",
    "<IDENTIFICADOR>",
    "\":\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
